### ISSUE TITLE
Add snapshot tests for generated files

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/java-spring-template#198]
#### Reason/Context
The template has accumulated a sufficient number of functions that can be affected by further improvements and changes in it. 
Integration tests that check the generated result allows to track changes in the generated files and functionality.

#### Description
Basic integration tests should cover generation of files (Config, MessageHandler, MessagePublisher, DTO) for existed test asyncapi files [kafka](tests/kafka.yml) and [mqtt](tests/mqtt.yml).
Features that also could be tested:
- [ ] all template parameters mentioned in README
- [ ] work with recursive model #150
- [ ] correct types for mandatory/optional fields #133
- [ ] correct types for date-time #95

Good example of snapshot testing could be found [here](https://github.com/asyncapi/nodejs-template/pull/103)
